### ISSUE TITLE
Incorrect part value

### ISSUE THREAD

**Issue by BrentWilkins** [sparkfun/RedStick#13]
The FTS31... Should be a FT231X...

**Comment by ToniCorinne** [comment]
As this change will update the IC silk, leaving as-is until a revision is needed.

**Comment by SFEMark** [comment]
Retired product. Closing issue.

**Comment by bboyho** [comment]
In case anyone was wondering, this looks like it was just the part name in the schematic and it did not require changes to the silkscreen in the board file.
